// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spotwchxqmryeafouaoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwb3R3Y2h4cW1yeWVhZm91YW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDAwODEsImV4cCI6MjA3NDQ3NjA4MX0.9sHTFBrfeZzAZIr0Dbtx3lGk-Niz_wNhGV_ubRANkgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});